version: "3.5"
services:
 
       
#########################################       
       
  nginx:
    build: ./nginx

    container_name: nginx

    volumes:
       - ./nginx/core:/etc/nginx/conf.d

    ports:
       - "80:80"

    networks:
       - net1
       - net2

    depends_on:
       - mysql
       - php
  

#########################################

    
    
  php:
    build: ./php
    container_name: php-fpm
    networks:
       - net2    

  
#########################################

  
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
       - MYSQL_ROOT_PASSWORD=$PASSWORD
    volumes:
       - ./mysql:/var/lib/mysql
    networks:
       - net2

##########################################

networks:
   net1:
        name: out
        driver: bridge
   net2: 
        name: local
        driver: bridge

