version: "3.5"
services:
 
       
#########################################       
       
  nginx:
    build: ./nginx

    container_name: nginx

    volumes:
       - ./nginx/core:/etc/nginx/conf.d
       - ./nginx/logs:/var/log/nginx

    ports:
       - "80:80"

    networks:
       - net1
       - net2

    depends_on:
       - mysql
       - php
  

#########################################

    
    
  php:
    build: ./php
    container_name: php-fpm
    ports: 
       - 9000    
    networks:
       - net2    

  
#########################################

  
  mysql:
    image: mysql:latest
    ports:
       - "3306:3306"
    container_name: mysql
    environment:
       - MYSQL_ROOT_PASSWORD=$PASSWORD

    networks:
       - net2

##########################################

networks:
   net1:
        name: out
        driver: bridge
   net2: 
        name: local
        driver: bridge

